servants = Troop.create(name: 'Servants')
Patrol.create(name: 'Chamois', troop: servants, money: 100)
Patrol.create(name: 'Puma', troop: servants, money: 100)
Patrol.create(name: 'Antilope', troop: servants, money: 100)
Patrol.create(name: 'Faucon', troop: servants, money: 100)
Patrol.create(name: 'Brocard', troop: servants, money: 100)
Patrol.create(name: 'Daim', troop: servants, money: 100)
City.create(name: 'Poitier', troop: servants, defense_building_multiplicator: 0)

archers = Troop.create(name: 'Archers')
Patrol.create(name: 'Chamois', troop: archers, money: 100)
Patrol.create(name: 'Puma', troop: archers, money: 100)
Patrol.create(name: 'Antilope', troop: archers, money: 100)
Patrol.create(name: 'Faucon', troop: archers, money: 100)
Patrol.create(name: 'Brocard', troop: archers, money: 100)
Patrol.create(name: 'Daim', troop: archers, money: 100)
City.create(name: 'Chartres', troop: archers, defense_building_multiplicator: 0)

paladins = Troop.create(name: 'Paladins')
Patrol.create(name: 'Chamois', troop: paladins, money: 100)
Patrol.create(name: 'Puma', troop: paladins, money: 100)
Patrol.create(name: 'Antilope', troop: paladins, money: 100)
Patrol.create(name: 'Faucon', troop: paladins, money: 100)
Patrol.create(name: 'Brocard', troop: paladins, money: 100)
Patrol.create(name: 'Daim', troop: paladins, money: 100)

# servants = Troop.create(name: 'Servants')
# Patrol.create(name: 'Chamois', troop: servants)
# Patrol.create(name: 'Puma', troop: servants)
# Patrol.create(name: 'Antilope', troop: servants)
# Patrol.create(name: 'Faucon', troop: servants)
# Patrol.create(name: 'Brocard', troop: servants)
# Patrol.create(name: 'Daim', troop: servants)
#
# servants = Troop.create(name: 'Servants')
# Patrol.create(name: 'Chamois', troop: servants)
# Patrol.create(name: 'Puma', troop: servants)
# Patrol.create(name: 'Antilope', troop: servants)
# Patrol.create(name: 'Faucon', troop: servants)
# Patrol.create(name: 'Brocard', troop: servants)
# Patrol.create(name: 'Daim', troop: servants)
#
# servants = Troop.create(name: 'Servants')
# Patrol.create(name: 'Chamois', troop: servants)
# Patrol.create(name: 'Puma', troop: servants)
# Patrol.create(name: 'Antilope', troop: servants)
# Patrol.create(name: 'Faucon', troop: servants)
# Patrol.create(name: 'Brocard', troop: servants)
# Patrol.create(name: 'Daim', troop: servants)
#
# servants = Troop.create(name: 'Servants')
# Patrol.create(name: 'Chamois', troop: servants)
# Patrol.create(name: 'Puma', troop: servants)
# Patrol.create(name: 'Antilope', troop: servants)
# Patrol.create(name: 'Faucon', troop: servants)
# Patrol.create(name: 'Brocard', troop: servants)
# Patrol.create(name: 'Daim', troop: servants)
#
# servants = Troop.create(name: 'Servants')
# Patrol.create(name: 'Chamois', troop: servants)
# Patrol.create(name: 'Puma', troop: servants)
# Patrol.create(name: 'Antilope', troop: servants)
# Patrol.create(name: 'Faucon', troop: servants)
# Patrol.create(name: 'Brocard', troop: servants)
# Patrol.create(name: 'Daim', troop: servants)
#
# servants = Troop.create(name: 'Servants')
# Patrol.create(name: 'Chamois', troop: servants)
# Patrol.create(name: 'Puma', troop: servants)
# Patrol.create(name: 'Antilope', troop: servants)
# Patrol.create(name: 'Faucon', troop: servants)
# Patrol.create(name: 'Brocard', troop: servants)
# Patrol.create(name: 'Daim', troop: servants)
