ingenieur = Guild.create(name: 'Ingénieur', attack_construction_cost_multiplicator: 0.7, mining_multiplicator: 1.3, revenues_multiplicator: 0.8)
constructeur = Guild.create(name: 'Constructeur', defense_construction_cost_multiplicator: 0.7, mining_multiplicator: 0.7, defense_power_multiplicator: 1.2)
marchand = Guild.create(name: 'Marchand', attack_power_multiplicator: 0.5, defense_power_multiplicator: 0.5, revenues_multiplicator: 3)
mercenaire = Guild.create(name: 'Mercenaire', attack_power_multiplicator: 2.2, defense_power_multiplicator: 1.5, mining_multiplicator: 0.2, revenues_multiplicator: 0)
arbaletrier = Guild.create(name: 'Arbalétrier', defense_power_multiplicator: 1.6)
mineur = Guild.create(name: 'Mineur', mining_multiplicator: 2, defense_power_multiplicator: 0.7)

servants = Troop.create(name: 'Servants')
Patrol.create(name: 'Chamois', troop: servants, money: 500, guild: arbaletrier)
Patrol.create(name: 'Puma', troop: servants, money: 500, guild: ingenieur)
Patrol.create(name: 'Antilope', troop: servants, money: 500, guild: constructeur)
Patrol.create(name: 'Faucon', troop: servants, money: 500, guild: marchand)
Patrol.create(name: 'Brocard', troop: servants, money: 500, guild: mercenaire)
Patrol.create(name: 'Daim', troop: servants, money: 500, guild: mineur)
City.create(name: 'Poitier', troop: servants, defense_building_multiplicator: 0)

archers = Troop.create(name: 'Archers')
Patrol.create(name: 'Dauphin', troop: archers, money: 500, guild: arbaletrier)
Patrol.create(name: 'Panda', troop: archers, money: 500, guild: ingenieur)
Patrol.create(name: 'Harfang', troop: archers, money: 500, guild: constructeur)
Patrol.create(name: 'Hafflinger', troop: archers, money: 500, guild: marchand)
Patrol.create(name: 'a', troop: archers, money: 500, guild: mercenaire)
Patrol.create(name: 'e', troop: archers, money: 500, guild: mineur)
City.create(name: 'Chartres', troop: archers, defense_building_multiplicator: 0)

paladins = Troop.create(name: 'Paladins')
Patrol.create(name: 'Husky', troop: paladins, money: 500, guild: arbaletrier)
Patrol.create(name: 'a', troop: paladins, money: 500, guild: ingenieur)
Patrol.create(name: 'b', troop: paladins, money: 500, guild: constructeur)
Patrol.create(name: 'c', troop: paladins, money: 500, guild: marchand)
Patrol.create(name: 'd', troop: paladins, money: 500, guild: mercenaire)
Patrol.create(name: 'e', troop: paladins, money: 500, guild: mineur)
City.create(name: 'Avignon', troop: paladins, defense_building_multiplicator: 0)

templiers = Troop.create(name: 'Templiers')
Patrol.create(name: 'Léopard', troop: templiers, money: 500, guild: arbaletrier)
Patrol.create(name: 'Seagull', troop: templiers, money: 500, guild: ingenieur)
Patrol.create(name: 'Otarie', troop: templiers, money: 500, guild: constructeur)
Patrol.create(name: 'Mangouste', troop: templiers, money: 500, guild: marchand)
Patrol.create(name: 'Gazelle', troop: templiers, money: 500, guild: mercenaire)
Patrol.create(name: 'Furet', troop: templiers, money: 500, guild: mineur)
City.create(name: 'Montruex', troop: templiers, defense_building_multiplicator: 0)

preux = Troop.create(name: 'Preux')
Patrol.create(name: 'Ecureuils', troop: preux, money: 500, guild: arbaletrier)
Patrol.create(name: 'Toucan', troop: preux, money: 500, guild: ingenieur)
Patrol.create(name: 'Lézard', troop: preux, money: 500, guild: constructeur)
Patrol.create(name: 'a', troop: preux, money: 500, guild: marchand)
Patrol.create(name: 'z', troop: preux, money: 500, guild: mercenaire)
Patrol.create(name: 'e', troop: preux, money: 500, guild: mineur)
City.create(name: 'Perpignan', troop: preux, defense_building_multiplicator: 0)

vaillants = Troop.create(name: 'Vaillants')
Patrol.create(name: 'e', troop: vaillants, money: 500, guild: arbaletrier)
Patrol.create(name: 'z', troop: vaillants, money: 500, guild: ingenieur)
Patrol.create(name: 'rzr', troop: vaillants, money: 500, guild: constructeur)
Patrol.create(name: 'tas', troop: vaillants, money: 500, guild: marchand)
Patrol.create(name: 'r', troop: vaillants, money: 500, guild: mercenaire)
Patrol.create(name: 'tre', troop: vaillants, money: 500, guild: mineur)
City.create(name: 'Reichemont', troop: vaillants, defense_building_multiplicator: 0)

chevaliers = Troop.create(name: 'Chevaliers')
Patrol.create(name: 'zaer', troop: chevaliers, money: 500, guild: arbaletrier)
Patrol.create(name: 'raze', troop: chevaliers, money: 500, guild: ingenieur)
Patrol.create(name: 'raze', troop: chevaliers, money: 500, guild: constructeur)
Patrol.create(name: 'zaeraze', troop: chevaliers, money: 500, guild: marchand)
Patrol.create(name: 'ttt', troop: chevaliers, money: 500, guild: mercenaire)
Patrol.create(name: 'trtt', troop: chevaliers, money: 500, guild: mineur)
City.create(name: 'Marseille', troop: chevaliers, defense_building_multiplicator: 0)

hardis = Troop.create(name: 'Hardis')
Patrol.create(name: 'r', troop: hardis, money: 500, guild: arbaletrier)
Patrol.create(name: 'razr', troop: hardis, money: 500, guild: ingenieur)
Patrol.create(name: 'zaeraz', troop: hardis, money: 500, guild: constructeur)
Patrol.create(name: 'gsfddg', troop: hardis, money: 500, guild: marchand)
Patrol.create(name: 'gsdg', troop: hardis, money: 500, guild: mercenaire)
Patrol.create(name: 'aaa', troop: hardis, money: 500, guild: mineur)
City.create(name: 'Mariencourt', troop: hardis, defense_building_multiplicator: 0)

gueux = Troop.create(name: 'Gueux')
Patrol.create(name: 'zear', troop: gueux, money: 500, guild: arbaletrier)
Patrol.create(name: 'raze', troop: gueux, money: 500, guild: ingenieur)
Patrol.create(name: 'dsfd', troop: gueux, money: 500, guild: constructeur)
Patrol.create(name: 'hhh', troop: gueux, money: 500, guild: marchand)
Patrol.create(name: 'ttt', troop: gueux, money: 500, guild: mercenaire)
Patrol.create(name: 'yii', troop: gueux, money: 500, guild: mineur)
City.create(name: 'Veux le vicomte', troop: gueux, defense_building_multiplicator: 0)

City.create(name: 'Paris', defense_building_multiplicator: 0)

Building.create(name: 'Trébuchet', usage: 'attack', durability: 2, multiplicator: 2, cost: 400)
Building.create(name: 'Bélier', usage: 'attack', durability: 1, multiplicator: 1.5, cost: 150)
Building.create(name: 'Tour de siège', usage: 'attack', durability: 1, multiplicator: 2, cost: 200)
Building.create(name: 'Mur de bois', usage: 'defense', multiplicator: 1.5, cost: 400)
Building.create(name: 'Mur de pierre', usage: 'defense', multiplicator: 2, cost: 600)
Building.create(name: 'Muraille', usage: 'defense', multiplicator: 2.5, cost: 800)
